### ISSUE TITLE
The first frame with long processing time

### ISSUE THREAD

**Issue by Hou-J-J** [pjrambo/VINS-Fusion-gpu#31]
Hi!
When testing the VINS-Fusion-gpu on TX2 nx, I encountered a problem that extracting features on the first frame with the function named goodFeaturesToTrack  takes a long time on TX2, which was about 20 to 30 seconds, I wonder how to solve this problem? Thanks.

**Comment by Dellaldd** [comment]
> Hi! When testing the VINS-Fusion-gpu on TX2 nx, I encountered a problem that extracting features on the first frame with the function named goodFeaturesToTrack takes a long time on TX2, which was about 20 to 30 seconds, I wonder how to solve this problem? Thanks.

Have you solved the issue? I met the same problem. Thank you for your help!

**Comment by yongyuan2023** [comment]
When the parameter "infra_fps" in rs_camera.launch is 15Hz, the problem is solved.

**Comment by Yehangbo** [comment]
> When the parameter "infra_fps" in rs_camera.launch is 15Hz, the problem is solved.

Hi！I tried this way in my orin NX, but i still have this issue. Thank you for your help!
